import XCTest
@testable import PocketDJ

/// CLOUD/DEVICE PARITY for the owner's 50% newcomer floor — the fixture is the law both
/// implementations are held to.
///
/// `apple/Tests/Fixtures/newcomer-parity.json` is generated by
/// `scripts/lambda/rec-engine/gen-newcomer-parity.mjs` THROUGH the Lambda's own exports
/// (`composeIncumbentCap` + `creditArtistKeys` — no third implementation), replayed by the Node
/// suite (self-check against regeneration drift) and by this one. The floor ships twice —
/// `RecComposition.compose` + `RecVersionIdentity.creditArtistKeys` here, `index.mjs` in the
/// Lambda — and the two MUST agree: a compose that seats one extra incumbent on one side, or a
/// credit split that reads a collaboration string as one artist on one side only, silently gives
/// the device tile and the cloud route different floors. Same arrangement as
/// `TimbreParityTests`, for the same reason.
final class NewcomerParityTests: XCTestCase {

    private struct Fixture: Decodable {
        struct CreditCase: Decodable {
            var raw: String
            var keys: [String]
        }
        struct Row: Decodable {
            var id: String
            var capKey: String
            var isIncumbent: Bool
        }
        struct CompositionCase: Decodable {
            var rows: [Row]
            var limit: Int
            var maxPerArtist: Int?
            var incumbentMaxShare: Double
            var out: [String]
        }
        var v: Int
        var credits: [CreditCase]
        var compositions: [CompositionCase]
    }

    private func loadFixture() throws -> Fixture {
        let url = try XCTUnwrap(
            Bundle(for: Self.self).url(forResource: "newcomer-parity", withExtension: "json"),
            "newcomer-parity.json must ship in the test bundle (Tests/Fixtures, via project.yml)")
        return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }

    /// The credit split — every name on a collaboration credit, in the Lambda's exact order.
    /// This is the incumbent identity ("Dinner Party, Terrace Martin, …" counts for a pocket
    /// holding ANY of those credits), so a single divergent key is a divergent floor.
    func testCreditSplitMatchesTheLambdaOnEveryFixtureCredit() throws {
        let fx = try loadFixture()
        XCTAssertGreaterThanOrEqual(fx.credits.count, 20, "the fixture must actually cover the traps")
        for c in fx.credits {
            XCTAssertEqual(RecVersionIdentity.creditArtistKeys(c.raw), c.keys,
                           "credit split diverged from the Lambda for \(String(reflecting: c.raw))")
        }
    }

    /// The compose — identical output lists for every generated case: random rankings over every
    /// knob (limit, artist cap incl. uncapped, share 0/0.34/0.5/1) plus the hand-written property
    /// cases (incumbent head pull-up, fail-open, odd-count rounding, under-cap passthrough).
    func testComposeMatchesTheLambdaOnEveryFixtureCase() throws {
        let fx = try loadFixture()
        XCTAssertGreaterThanOrEqual(fx.compositions.count, 40)
        for (i, c) in fx.compositions.enumerated() {
            let rows = c.rows.map {
                RecComposition.Row(id: $0.id, capKey: $0.capKey, isIncumbent: $0.isIncumbent)
            }
            let out = RecComposition.compose(rows, limit: c.limit, maxPerArtist: c.maxPerArtist,
                                             incumbentMaxShare: c.incumbentMaxShare)
            XCTAssertEqual(out, c.out, "composition case \(i) diverged from the Lambda")
        }
    }

    /// The floor holds on every fixture case at the shipped 0.5 — incumbents never exceed
    /// ⌊n·share⌋ UNLESS the newcomer pool genuinely ran dry (fail open). Asserted over the
    /// UNCAPPED cases, where "dry" is exact: with no artist budget in play, exceeding the cap is
    /// only legitimate when every newcomer in the ranking was already seated. (The artist-capped
    /// cases are pinned list-for-list by the parity test above.)
    func testTheFloorAndTheFailOpenHoldAcrossTheFixture() throws {
        let fx = try loadFixture()
        var checked = 0
        for (i, c) in fx.compositions.enumerated()
        where c.incumbentMaxShare == 0.5 && c.maxPerArtist == nil {
            checked += 1
            let byId = Dictionary(c.rows.map { ($0.id, $0) }, uniquingKeysWith: { a, _ in a })
            let inc = c.out.compactMap { byId[$0] }.filter(\.isIncumbent).count
            let cap = Int((Double(c.out.count) * c.incumbentMaxShare).rounded(.down))
            if inc > cap {
                let newcomersAvailable = c.rows.filter { !$0.isIncumbent }.count
                XCTAssertEqual(c.out.count - inc, newcomersAvailable,
                    "case \(i): incumbents over the cap without the newcomer pool being dry")
            }
        }
        XCTAssertGreaterThan(checked, 0, "the fixture must include uncapped 0.5-share cases")
    }
}
