import XCTest
@testable import PocketDJ

/// CLOUD/DEVICE PARITY for the timbre math — the fixture is the law both implementations are
/// held to.
///
/// `apple/Tests/Fixtures/timbre-parity.json` is generated by
/// `scripts/lambda/rec-engine/gen-timbre-parity.mjs` THROUGH the Lambda's own exported functions
/// (no third implementation), replayed by the Node suite (self-check against regeneration drift)
/// and by this one. The timbre distance/profile/fit ships twice — `SimilarityFamilies` here,
/// `index.mjs` in the Lambda — and the two MUST agree to float precision, or the local tile and
/// the cloud tile quietly disagree about what a crate sounds like: the parallel-identity-check
/// bug this app has been bitten by before, now on the similarity axis. This is why there is ONE
/// distance (F10's RMS) and a fixture pinning it, rather than two drifting copies.
final class TimbreParityTests: XCTestCase {

    // ── The fixture document ─────────────────────────────────────────────────
    private struct Fixture: Decodable {
        struct DistanceCase: Decodable {
            var a: [String: Double]
            var b: [String: Double]
            var d: Double?
        }
        struct Member: Decodable {
            var f: [String: Double]
            var w: Double
        }
        struct Profile: Decodable {
            var centroid: [String: Double]
            var spread: Double
            var vectors: Int
        }
        struct Negative: Decodable {
            var members: [Member]
            var profile: Profile?
        }
        struct ProfileCase: Decodable {
            var members: [Member]
            var minVectors: Int
            var probe: [String: Double]
            var negative: Negative?
            var profile: Profile?
            var fit: Double?
            var netFit: Double?
            var adjectives: [String]?
        }
        struct AdjectiveCase: Decodable {
            var centroid: [String: Double]
            var words: [String]
        }
        var v: Int
        var distances: [DistanceCase]
        var profiles: [ProfileCase]
        var adjectiveCases: [AdjectiveCase]
    }

    private func loadFixture() throws -> Fixture {
        let url = try XCTUnwrap(
            Bundle(for: Self.self).url(forResource: "timbre-parity", withExtension: "json"),
            "timbre-parity.json must ship in the test bundle (Tests/Fixtures, via project.yml)")
        return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }

    private let accuracy = 1e-9

    func testDistancesMatchTheLambdaExactly() throws {
        let fx = try loadFixture()
        XCTAssertGreaterThanOrEqual(fx.distances.count, 50, "the fixture is not a stub")
        for (i, c) in fx.distances.enumerated() {
            let d = SimilarityFamilies.timbreDistance(c.a, c.b)
            if let expected = c.d {
                XCTAssertEqual(try XCTUnwrap(d, "case \(i) must be comparable"), expected,
                               accuracy: accuracy, "distance drift on case \(i)")
            } else {
                XCTAssertNil(d, "case \(i): under 8 shared axes both sides refuse to compare")
            }
        }
    }

    func testProfilesFitsAndNetFitsMatchTheLambdaExactly() throws {
        let fx = try loadFixture()
        XCTAssertGreaterThanOrEqual(fx.profiles.count, 20, "the fixture is not a stub")
        for (i, c) in fx.profiles.enumerated() {
            let p = SimilarityFamilies.timbreProfile(c.members.map { (vector: $0.f, weight: $0.w) },
                                                     minVectors: c.minVectors)
            guard let expected = c.profile else {
                XCTAssertNil(p, "case \(i): below the liveness bar both sides produce NO profile")
                continue
            }
            let profile = try XCTUnwrap(p, "case \(i) must be live")
            XCTAssertEqual(profile.vectors, expected.vectors, "case \(i) vector count")
            XCTAssertEqual(profile.spread, expected.spread, accuracy: accuracy, "case \(i) spread")
            XCTAssertEqual(Set(profile.centroid.keys), Set(expected.centroid.keys),
                           "case \(i): the two sides agree which axes the centroid carries")
            for (axis, v) in expected.centroid {
                XCTAssertEqual(try XCTUnwrap(profile.centroid[axis]), v, accuracy: accuracy,
                               "case \(i) centroid drift on \(axis)")
            }
            let fit = SimilarityFamilies.timbreFit(c.probe, profile: profile)
            if let expectedFit = c.fit {
                XCTAssertEqual(try XCTUnwrap(fit), expectedFit, accuracy: accuracy, "case \(i) fit")
            } else {
                XCTAssertNil(fit, "case \(i): an incomparable probe is 'no vector' on both sides")
            }
            if let neg = c.negative, neg.profile != nil, let expectedNet = c.netFit {
                let negProfile = SimilarityFamilies.timbreProfile(
                    neg.members.map { (vector: $0.f, weight: $0.w) }, minVectors: 1)
                let net = SimilarityFamilies.timbreNetFit(c.probe, positive: profile,
                                                          negative: negProfile,
                                                          rejectionWeight: 0.5)
                XCTAssertEqual(try XCTUnwrap(net), expectedNet, accuracy: accuracy,
                               "case \(i) net fit (the 👎 subtraction must agree too)")
            }
            if let words = c.adjectives {
                XCTAssertEqual(SimilarityFamilies.timbreAdjectives(profile.centroid), words,
                               "case \(i): the why-string vocabulary must not drift between sides")
            }
        }
    }

    func testAdjectiveTableMatchesTheLambdaExactly() throws {
        let fx = try loadFixture()
        for (i, c) in fx.adjectiveCases.enumerated() {
            XCTAssertEqual(SimilarityFamilies.timbreAdjectives(c.centroid), c.words,
                           "adjective case \(i)")
        }
    }
}
